export const CustomerActionTypes = {
    GET_CUSTOMER:'GET_CUSTOMER',
    SET_CUSTOMER:'SET_CUSTOMER',
    UPDATE_CUSTOMER:'UPDATE_CUSTOMER',
    DELETE_CUSTOMER:'DELETE_CUSTOMER',
    GET_CUSTOMERS_BY_SEARCH: 'GET_CUSTOMERS_BY_SEARCH',
    CUSTOMERS_ERROR: 'CUSTOMERS_ERROR'
}