export const TransactionActionTypes = {
    GET_TRANSACTIONS: 'GET_TRANSACTIONS',
    SET_TRANSACTION: 'SET_TRANSACTION',
    DELETE_TRANSACTION: 'DELETE_TRANSACTION',
    GET_TRANSACTIONS_BY_SEARCH: 'GET_TRANSACTIONS_BY_SEARCH',
    TRANSACTION_ERROR: 'TRANSACTION_ERROR'
}