export const AccountActionTypes = {
    GET_ACCOUNT: 'GET_ACCOUNT',
    GET_ACCOUNTS: 'GET_ACCOUNTS',
    SET_ACCOUNT: 'SET_ACCOUNT',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
    ACCOUNT_ERROR: 'ACCOUNT_ERROR'
}